### ISSUE TITLE
小白提问

### ISSUE THREAD

**Issue by pravezhang** [yeyupiaoling/VoiceprintRecognition-PaddlePaddle#11]
请问各位大佬，我这边有几百条标记好讲话人的语音作为训练集，打算之后用训练好的模型去给更多的语音标记讲话人。

那我是直接拿我的这几百条去训练和使用，还是先用[zhvoice](https://aistudio.baidu.com/aistudio/datasetdetail/133922) 的数据训练完，再用我自己这几百条去训练呢？

**Comment by yeyupiaoling** [comment]
并不一定要训练呢。你直接可以使用模型来做声纹识别。你非要训练的话，你那点数据也没有用。不过你可以跟那个数据集合，并一起训练。

**Comment by pravezhang** [comment]
我下载了你的超大数据集训练过的模型，和zhvoice训练的MFCC处理的模型，然后试了几个声纹区分，每个相似度都是0.96+，没办法直接用。。。

**Comment by pravezhang** [comment]
拿zhvoice 和我这几百条共同训练的话，我这几百条是不是杯水车薪基本不会改变模型的训练结果呀？

**Comment by pravezhang** [comment]
请问有什么好的解决方案或优化方法吗？

**Comment by yeyupiaoling** [comment]
你测过项目自带的那两个文件吗？他们相似度是多少？
你下载的文件有没有全部复制到项目根目录里面替换掉原来的？

**Comment by pravezhang** [comment]
> 

试了一下，a_2和b_2也是97%， a_1 和b_2 是99%……

![image](https://github.com/yeyupiaoling/VoiceprintRecognition-PaddlePaddle/assets/41674776/20a540a5-ae6a-4b4d-9f70-df497d959e77)
我的目录是这样的，请问有什么地方需要修改参数或者文件没放对地方吗

**Comment by yeyupiaoling** [comment]
应该是你下载了旧的模型吧。下载最新的模型，然后替换掉项目原来的文件。
