### ISSUE TITLE
请问大佬有木有训练好的模型？

### ISSUE THREAD

**Issue by zhangyifei1** [yeyupiaoling/VoiceprintRecognition-PaddlePaddle#2]

**Comment by yeyupiaoling** [comment]
看文档

**Comment by zlszhonglongshen** [comment]
> 看文档

大佬 是收费的哦？能不能开源高一个？

**Comment by yeyupiaoling** [comment]
@zlszhonglongshen 你可以看这个文档， 下载数据集自行训练一个，训练过程很简单的。
https://github.com/yeyupiaoling/VoiceprintRecognition-PaddlePaddle#%E5%88%9B%E5%BB%BA%E6%95%B0%E6%8D%AE

**Comment by zhangyifei1** [comment]
才几块钱而已，你不会真的想白嫖吧【狗头】【狗头】

**Comment by zlszhonglongshen** [comment]
> 才几块钱而已，你不会真的想白嫖吧【狗头】【狗头】

想先拿来试试 【狗头】
