### ISSUE TITLE
采集的音频去静音处理

### ISSUE THREAD

**Issue by dyfcode** [yeyupiaoling/VoiceprintRecognition-PaddlePaddle#3]
想通过对采集的音频进行去静音处理提高识别率，请问大佬有什么好的方法没？

**Comment by yeyupiaoling** [comment]
目前没有

**Comment by dyfcode** [comment]
明白了，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月24日(周四) 上午9:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yeyupiaoling/VoiceprintRecognition-PaddlePaddle] 采集的音频去静音处理 (Issue #3)




 
Closed #3.

**Comment by HandsLing** [comment]
有开源包可以检测静音、拼接音频的，可以试试，pydub，这个包了解一下
