### ISSUE TITLE
数据读取慢

### ISSUE THREAD

**Issue by jiangxin3** [yeyupiaoling/VoiceprintRecognition-PaddlePaddle#5]
将中文语音语料数据集下载好后，运行create_data.py发现数据读取非常的慢
![image](https://user-images.githubusercontent.com/104053530/164608993-a7176dd7-ce46-4fd8-9b66-3eae556a23b9.png)

**Comment by yeyupiaoling** [comment]
这个是制作数据，未来加快训练时数据读取，要把mp3转换成wav，所有速度慢一些。
不过你的也太慢了，我的一天就完成了。

**Comment by jiangxin3** [comment]
我虚拟机的配置是8核64G内存，不应该跑这么慢啊，是不是由于paddlepaddle版本或者librosa版本造成的呢

**Comment by yeyupiaoling** [comment]
我的是16核，
这是制作数据，还没到训练，用不到paddlepaddle和librosa
