### ISSUE TITLE
转onnx报错

### ISSUE THREAD

**Issue by HandsLing** [yeyupiaoling/VoiceprintRecognition-PaddlePaddle#6]
老哥，你试过你新改的这个代码转onnx吗？好像不成功
File "/data1/sda/lingck/VoiceRecogntion/VoiceprintRecognition-PaddlePaddle/modules/ecapa_tdnn.py", line 186, in forward
                y_i = self.blocks[i - 1](x_i)
            else:
                y_i = self.blocks[i - 1](x_i + y_i)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            y.append(y_i)
        y = paddle.concat(y, axis=1)


    UnboundLocalError: local variable 'y_i' referenced before assignment

**Comment by yeyupiaoling** [comment]
这个模型还不支持冻结。

**Comment by HandsLing** [comment]
。。。。。。
后面会支持吗？

**Comment by yeyupiaoling** [comment]
不是所有动态图都能转成静态图的。

**Comment by yeyupiaoling** [comment]
如果你非要用静态图，可以版本1：https://github.com/yeyupiaoling/VoiceprintRecognition-PaddlePaddle/tree/V1.0

**Comment by HandsLing** [comment]
嗯 我之前跑过版本1的 但是我看了版本2更灵活、速度更快就想试试，
