### ISSUE TITLE
ValueError: The ``path`` (models/ecapa_tdnn/model.pdparams) to load model not exists.

### ISSUE THREAD

**Issue by Amaiyeye** [yeyupiaoling/VoiceprintRecognition-PaddlePaddle#8]
大佬我执行 python3 infer_contrast.py --audio_path1=audio/a_1.wav --audio_path2=audio/b_2.wav 的时候报 ValueError: The ``path`` (models/ecapa_tdnn/model.pdparams) to load model not exists. 同时我没有安装PaddlePaddle的Inference预测库，因为我在安装的时候总是报不适用当前的平台，但是其他环境我都安装完了，是因为这个的原因吗？顺便PaddlePaddle的Inference预测库只能是Nvidia Jetson吗？

**Comment by yeyupiaoling** [comment]
首先你没有下载模型放在根目录
没有报paddlePaddle不存在，应该安装了的
官方给的PaddlePaddle的Nvidia Jetson只有Inference，你试试能不能自己编译

**Comment by Amaiyeye** [comment]
好的，谢谢大佬
